---
sidebar: sidebar 
permalink: reference_limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, cloud manager, Cloud Volumes ONTAP, days, 14 days, running, Connectors should remain running 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni. 
---
= Limitazioni note
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le limitazioni note identificano piattaforme, dispositivi o funzioni non supportate da questa versione del prodotto o che non interagiscono correttamente con esso. Esaminare attentamente queste limitazioni.



== I connettori devono rimanere in funzione

Un connettore deve rimanere sempre in funzione. È importante per la salute e il funzionamento continui dei servizi che si abilitano.

Ad esempio, un connettore è un componente chiave per lo stato e il funzionamento dei sistemi PAYGO di Cloud Volumes ONTAP. Se un connettore viene spento, i sistemi PAYGO di Cloud Volumes ONTAP si spegneranno dopo aver perso la comunicazione con un connettore per più di 14 giorni.



== La piattaforma SaaS è disattivata per le regioni governative

Se si implementa un connettore in un'area AWS GovCloud, Azure Gov o Azure DoD, l'accesso a Cloud Manager è disponibile solo tramite l'indirizzo IP host di un connettore. L'accesso alla piattaforma SaaS è disattivato per l'intero account.

Ciò significa che solo gli utenti con privilegi che possono accedere al VPC/VNET interno dell'utente finale possono utilizzare l'interfaccia utente o l'API di Cloud Manager.

Significa inoltre che i seguenti servizi non sono disponibili da Cloud Manager:

* Conformità al cloud
* Kubernetes
* Tiering nel cloud
* Global file cache
* Monitoraggio (Cloud Insights)


Per utilizzare questi servizi è necessaria la piattaforma SaaS.



== Gli host Linux condivisi non sono supportati

Il connettore non è supportato su un host condiviso con altre applicazioni. L'host deve essere un host dedicato.



== Cloud Manager non supporta i volumi FlexGroup

Anche se Cloud Volumes ONTAP supporta FlexGroup Volumes, non lo fa. Se si crea un volume FlexGroup da Gestore di sistema o dall'interfaccia CLI, impostare la modalità di gestione della capacità di Cloud Manager su Manuale. La modalità automatica potrebbe non funzionare correttamente con i volumi FlexGroup.
