---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: La configurazione predefinita di Cloud Volumes ONTAP consente di configurare e amministrare i sistemi, in particolare se si conosce ONTAP perché la configurazione predefinita di Cloud Volumes ONTAP è diversa da ONTAP. 
---
= Configurazione predefinita per Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La configurazione predefinita di Cloud Volumes ONTAP consente di configurare e amministrare i sistemi, in particolare se si conosce ONTAP perché la configurazione predefinita di Cloud Volumes ONTAP è diversa da ONTAP.



== Valori predefiniti

* Cloud Volumes ONTAP è disponibile come sistema a nodo singolo in AWS, Azure e GCP e come coppia ha in AWS e Azure.
* Cloud Manager crea una VM di storage per il servizio dei dati quando implementa Cloud Volumes ONTAP. Alcune configurazioni supportano macchine virtuali storage aggiuntive. link:task_managing_svms.html["Scopri di più sulla gestione delle VM di storage"].
* Cloud Manager installa automaticamente le seguenti licenze ONTAP Feature su Cloud Volumes ONTAP:
+
** CIFS
** FlexCache
** FlexClone
** ISCSI
** NetApp Volume Encryption (solo per sistemi BYOL o PAYGO registrati)
** NFS
** SnapMirror
** SnapRestore
** SnapVault


* Per impostazione predefinita, vengono create diverse interfacce di rete:
+
** Una LIF di gestione del cluster
** Un LIF intercluster
** LIF di gestione SVM su sistemi ha in Azure, sistemi a nodo singolo in AWS e, facoltativamente, su sistemi ha in più zone di disponibilità AWS
** Una LIF di gestione dei nodi
** Una LIF di dati iSCSI
** Una LIF di dati CIFS e NFS
+

NOTE: Il failover LIF è disattivato per impostazione predefinita per Cloud Volumes ONTAP a causa dei requisiti EC2. La migrazione di una LIF a una porta diversa interrompe la mappatura esterna tra gli indirizzi IP e le interfacce di rete sull'istanza, rendendo la LIF inaccessibile.



* Cloud Volumes ONTAP invia i backup della configurazione al connettore utilizzando HTTPS.
+
I backup sono accessibili da https://ipaddress/occm/offboxconfig/[] Dove _ipaddress_ è l'indirizzo IP dell'host del connettore.

* Cloud Manager imposta alcuni attributi di volume in modo diverso rispetto ad altri strumenti di gestione (ad esempio, System Manager o CLI).
+
La tabella seguente elenca gli attributi del volume impostati da Cloud Manager in modo diverso dai valori predefiniti:

+
[cols="15,85"]
|===
| Attributo | Valore stabilito da Cloud Manager 


| Modalità di dimensionamento automatico | crescere 


| Dimensionamento automatico massimo  a| 
1,000%


NOTE: L'amministratore dell'account può modificare questo valore dalla pagina Impostazioni.



| Stile di sicurezza | NTFS per CIFS Volumes UNIX per NFS Volumes 


| Stile garanzia di spazio | nessuno 


| Autorizzazioni UNIX (solo NFS) | 777 
|===
+
Per informazioni su questi attributi, consulta la pagina man _volume create_.





== Dati di boot e root per Cloud Volumes ONTAP

Oltre allo storage per i dati degli utenti, Cloud Manager acquista anche lo storage cloud per i dati di boot e root su ogni sistema Cloud Volumes ONTAP.



=== AWS

* Due dischi per nodo per i dati di boot e root:
+
** 9.7: Disco io1 da 160 GB per i dati di avvio e disco gp2 da 220 GB per i dati root
** 9.6: Disco io1 da 93 GB per i dati di avvio e disco gp2 da 140 GB per i dati root
** 9.5: Disco io1 da 45 GB per i dati di avvio e disco gp2 da 140 GB per i dati root


* Un'istantanea EBS per ogni disco di boot e disco root
* Per le coppie ha, un volume EBS per l'istanza Mediator, che è di circa 8 GB




=== Azure (nodo singolo)

* Tre dischi SSD Premium:
+
** Un disco da 10 GB per i dati di avvio
** Un disco da 140 GB per i dati root
** Un disco da 128 GB per NVRAM
+
Se la macchina virtuale scelta per Cloud Volumes ONTAP supporta gli SSD Ultra, il sistema utilizza un SSD Ultra per la NVRAM, anziché un SSD Premium.



* Un disco HDD standard da 1024 GB per il risparmio dei core
* Uno snapshot Azure per ogni disco di boot e disco root




=== Azure (coppie ha)

* Due dischi SSD Premium da 10 GB per il volume di boot (uno per nodo)
* Due blob di pagina Premium Storage da 140 GB per il volume root (uno per nodo)
* Due dischi HDD standard da 1024 GB per il risparmio di core (uno per nodo)
* Due dischi SSD Premium da 128 GB per NVRAM (uno per nodo)
* Uno snapshot Azure per ogni disco di boot e disco root




=== GCP

* Un disco persistente standard da 10 GB per i dati di avvio
* Un disco persistente standard da 64 GB per i dati root
* Un disco persistente standard da 500 GB per NVRAM
* Un disco persistente standard da 216 GB per il risparmio dei core
* Uno snapshot GCP per il disco di boot e il disco root




=== Dove risiedono i dischi

Cloud Manager definisce lo storage come segue:

* I dati di avvio risiedono su un disco collegato all'istanza o alla macchina virtuale.
+
Questo disco, che contiene l'immagine di avvio, non è disponibile per Cloud Volumes ONTAP.

* I dati root, che contengono la configurazione del sistema e i log, risiedono in aggr0.
* Il volume root della macchina virtuale di storage (SVM) risiede in aggr1.
* I volumi di dati risiedono anche in aggr1.




=== Crittografia

I dischi di boot e root sono sempre crittografati in Azure e Google Cloud Platform perché la crittografia è attivata per impostazione predefinita in tali provider cloud.

Quando si attiva la crittografia dei dati in AWS utilizzando il servizio di gestione delle chiavi (KMS), vengono crittografati anche i dischi di avvio e i dischi root per Cloud Volumes ONTAP. Questo include il disco di boot per l'istanza del mediatore in una coppia ha. I dischi vengono crittografati utilizzando la CMK selezionata quando si crea l'ambiente di lavoro.
